
spring:
  datasource:
    url: jdbc:mariadb:springbootdb
    driver-class-name: org.mariadb.jdbc.Driver
    username: juan
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true 
    
