
spring:
  datasource:
    url: postgres://faxdbnavwxcjpl:4bb27733244560903a4f6f2e7b276e48eb25d3c4a4f882caf05948f32942051f@ec2-18-210-64-223.compute-1.amazonaws.com:5432/dbnfssqetnc1tr
    username: faxdbnavwxcjpl
    password: 4bb27733244560903a4f6f2e7b276e48eb25d3c4a4f882caf05948f32942051f

  jpa:
    database-platform: org.hibernate.dialect.PostgresSQL10Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true 
    
